[package]
name = "lending_chain"
version = "0.1.0"
description = "LendingChain Non-Custodial Micro-Loan Escrow on Solana"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "lending_chain"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.30.1"
